# Generated by Django 4.2.20 on 2025-03-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
