name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DB_NAME='defaultdb'" >> $GITHUB_ENV
        echo "DB_USER='avnadmin'" >> $GITHUB_ENV
        echo "DB_PASSWORD='AVNS_ZGun_pVu84A4xbJmZcx'" >> $GITHUB_ENV
        echo "DB_HOST='pg-magnum00-blossom-poetry.c.aivencloud.com'" >> $GITHUB_ENV
        echo "DB_PORT='22436'" >> $GITHUB_ENV
        echo "SECRET_KEY='q6v9&z7x!j@p2l#d0w^r8s3m$g*t1b5y(kc%x+aoefu4hjn'" >> $GITHUB_ENV

    - name: Build Static
      run: |
        python manage.py collectstatic --no-input

    - name: Run Tests
      run: |
        python manage.py test
